# Agent Control Panel · Juno

_Module 5. Generated by `M5 - Agent Control Panel.html`. Paste over `05-agentic-workflows/agent-control-panel.md`._

## Autonomy level

**Level 2 — acts within a sandbox, humans own consequences.**

- Agent CAN read dispute reports, look up the disputed records, classify, compute the daily dispute rate, create Jira stubs, and post digests/alerts.
- Agent CANNOT update pension payment history, HR or identity records, edit Jira after creation, contact members, or take the site down.

## Controls

- **Kill switch:** `max_steps = 8`; 90 s wall-clock. Abort and post a failure notice if any payments/HR lookup fails twice, if a write is attempted outside the allow-list, or if the run exceeds either limit. Ops flag `juno.agent.enabled = false` halts all runs.
- **Rate / cost caps:** ≤ 200 `payments.lookup` calls per run; ≤ 3 Jira stubs per run; ≤ 2 Slack posts per run; ≤ $2 model spend per run; one scheduled run per day plus event-triggered runs capped at 6/day.
- **Escalate-on-stuck:** two consecutive failed runs → page `@on-call-pm`; three → agent disables itself until a human re-enables.

## Monitoring

**Confidence thresholds (map to actions):**

| Signal | Threshold | Action |
|---|---|---|
| Per-report classification confidence | < 70% | Mark `needs human`, no suggested action |
| Daily dispute rate | < 5% | Digest → `#pm-daily` (after 5-min PM review window) |
| Daily dispute rate | 5–15% | Alert → `#escalations`, tag `@on-call-pm`, Jira stub |
| Daily dispute rate | > 15% | P0 alert → `#escalations`; **recommend** maintenance mode; on-call PM + eng confirm and execute |
| Cluster | ≥ 10 reports on one payment source in a day | Jira stub regardless of overall rate |

**Checkpoints:** before every write (Jira stub, Slack post) the agent re-checks the channel/tool is on the allow-list and that the payload contains no PII (regex + field whitelist).

**North Star (re-read every loop):**

> You are Juno's triage agent. Turn member payment disputes into a cited, PII-free daily picture of data quality for the PM, and escalate when the picture says the data is broken — never touch the data yourself.

## Permissions

| | Scope |
|---|---|
| **Read** | Slack `#escalations`; Pension Payments DB (record lookup by payment_id/member_id); HR system (eligibility); analytics (daily view counts); Pension Handbook KB |
| **Write** | Slack `#pm-daily`, Slack `#escalations`; Jira stub creation |
| **Never** | Payments DB, HR, identity or Salesforce records; Jira edits; any other Slack channel; email/SMS to members |

## Self-review

- [x] Stop conditions include max_steps + wall-clock timeout.
- [x] Tool outputs include a confidence/score field per retrieval tool (classification schema in AWSpec).
- [x] Confidence thresholds map to actions, not just labels.
- [x] North Star is one sentence, re-read every loop.
- [x] Each rule of engagement names something the agent CANNOT do.
